Feat/bo 2381/create dynamic header transmutation plugin
inventi/traefik-header-transmute pull request #1
Opened 2022-08-17 14:47 UTC by dariusandz

2022-08-22 12:02 UTC, Zilv1nas requested changes

2022-08-22 12:02 UTC, Zilv1nas commented on LICENCE
> +Copyright (c) 2022 dariusandz
darius or inventi?

2022-08-22 12:02 UTC, Zilv1nas commented on go.mod
> +require (
are these packages necessary?

2022-08-22 12:02 UTC, Zilv1nas commented on transmute_headers.go
> +		//return nil, fmt.Errorf("could not extract mapping from env key %s", config.MappingEnvKey)
If this is commented out, then what's the point of this block?

2022-08-24 06:32 UTC, dariusandz commented on transmute_headers.go
> +		//return nil, fmt.Errorf("could not extract mapping from env key %s", config.MappingEnvKey)
Removed

2022-08-24 06:32 UTC, dariusandz commented on go.mod
> +require (
They are added automatically with `go mod tidy` so I'm guessing they are

2022-08-24 06:32 UTC, dariusandz commented on LICENCE
> +Copyright (c) 2022 dariusandz
Inventi

2022-08-24 06:46 UTC, Zilv1nas approved these changes

2022-08-24 06:46 UTC, merged